spring.application.name=FoodDeliveryApp

spring.datasource.url=jdbc:mysql://localhost:3306/fooddelivery_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=KJHgfdsAqwertyuiopZXCVBNmlkjhgfdsQWERTYUIOPa==

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Delivery Status Messaging
delivery.status.queue=delivery-status-queue
delivery.status.exchange=delivery-status-exchange
delivery.status.routing-key=delivery.status.update